In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
%matplotlib inline

In [37]:
dataset = tf.data.Dataset.from_tensor_slices([[1,2],[3,4],[5,6]])

In [38]:
dataset

<TensorSliceDataset shapes: (2,), types: tf.int32>

In [39]:
for element in dataset:
    print(element)

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([3 4], shape=(2,), dtype=int32)
tf.Tensor([5 6], shape=(2,), dtype=int32)


In [40]:
 for element in dataset:
    print(element.numpy())

[1 2]
[3 4]
[5 6]


In [41]:
dataset_dic  = tf.data.Dataset.from_tensor_slices(
{'a':[1,2,3,4],"b":[5,6,7,8],"c":[9,10,11,12]})

In [42]:
dataset_dic

<TensorSliceDataset shapes: {a: (), b: (), c: ()}, types: {a: tf.int32, b: tf.int32, c: tf.int32}>

In [43]:
for ele in dataset_dic:
    print(ele)

{'a': <tf.Tensor: id=162, shape=(), dtype=int32, numpy=1>, 'b': <tf.Tensor: id=163, shape=(), dtype=int32, numpy=5>, 'c': <tf.Tensor: id=164, shape=(), dtype=int32, numpy=9>}
{'a': <tf.Tensor: id=165, shape=(), dtype=int32, numpy=2>, 'b': <tf.Tensor: id=166, shape=(), dtype=int32, numpy=6>, 'c': <tf.Tensor: id=167, shape=(), dtype=int32, numpy=10>}
{'a': <tf.Tensor: id=168, shape=(), dtype=int32, numpy=3>, 'b': <tf.Tensor: id=169, shape=(), dtype=int32, numpy=7>, 'c': <tf.Tensor: id=170, shape=(), dtype=int32, numpy=11>}
{'a': <tf.Tensor: id=171, shape=(), dtype=int32, numpy=4>, 'b': <tf.Tensor: id=172, shape=(), dtype=int32, numpy=8>, 'c': <tf.Tensor: id=173, shape=(), dtype=int32, numpy=12>}


In [53]:
dataset  = tf.data.Dataset.from_tensor_slices(np.array([1,2,3,4,5,6]))

In [45]:
for ele in dataset.take(4):
    print(ele)

tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)


In [46]:
next(iter(dataset.take(1)))

<tf.Tensor: id=194, shape=(), dtype=int64, numpy=1>

In [49]:
dataset = dataset.repeat(count=3) #乱序重复3次

In [58]:
for ele in dataset:
    print(ele.numpy())

1
4
9
16
25
36


In [51]:
dataset = dataset.batch(3)

In [57]:
dataset = dataset.map(tf.square)